// Code generated by help.awk. DO NOT EDIT.
// GENERATED FILE DO NOT EDIT

package parser

var helpMessages = map[string]HelpMessageBody{
	//line sql.y: 1097
	`ALTER`: {
		//line sql.y: 1098
		Category: hGroup,
		//line sql.y: 1099
		Text: `ALTER TABLE, ALTER INDEX, ALTER VIEW, ALTER SEQUENCE, ALTER DATABASE, ALTER USER
`,
	},
	//line sql.y: 1114
	`ALTER TABLE`: {
		ShortDescription: `change the definition of a table`,
		//line sql.y: 1115
		Category: hDDL,
		//line sql.y: 1116
		Text: `
ALTER TABLE [IF EXISTS] <tablename> <command> [, ...]

Commands:
  ALTER TABLE ... ADD [COLUMN] [IF NOT EXISTS] <colname> <type> [<qualifiers...>]
  ALTER TABLE ... ADD <constraint>
  ALTER TABLE ... DROP [COLUMN] [IF EXISTS] <colname> [RESTRICT | CASCADE]
  ALTER TABLE ... DROP CONSTRAINT [IF EXISTS] <constraintname> [RESTRICT | CASCADE]
  ALTER TABLE ... ALTER [COLUMN] <colname> {SET DEFAULT <expr> | DROP DEFAULT}
  ALTER TABLE ... ALTER [COLUMN] <colname> DROP NOT NULL
  ALTER TABLE ... ALTER [COLUMN] <colname> DROP STORED
  ALTER TABLE ... ALTER [COLUMN] <colname> [SET DATA] TYPE <type> [COLLATE <collation>]
  ALTER TABLE ... RENAME TO <newname>
  ALTER TABLE ... RENAME [COLUMN] <colname> TO <newname>
  ALTER TABLE ... VALIDATE CONSTRAINT <constraintname>
  ALTER TABLE ... SPLIT AT <selectclause> [WITH EXPIRATION <expr>]
  ALTER TABLE ... UNSPLIT AT <selectclause>
  ALTER TABLE ... UNSPLIT ALL
  ALTER TABLE ... SCATTER [ FROM ( <exprs...> ) TO ( <exprs...> ) ]
  ALTER TABLE ... INJECT STATISTICS ...  (experimental)
  ALTER TABLE ... PARTITION BY RANGE ( <name...> ) ( <rangespec> )
  ALTER TABLE ... PARTITION BY LIST ( <name...> ) ( <listspec> )
  ALTER TABLE ... PARTITION BY NOTHING
  ALTER TABLE ... CONFIGURE ZONE <zoneconfig>

Column qualifiers:
  [CONSTRAINT <constraintname>] {NULL | NOT NULL | UNIQUE | PRIMARY KEY | CHECK (<expr>) | DEFAULT <expr>}
  FAMILY <familyname>, CREATE [IF NOT EXISTS] FAMILY [<familyname>]
  REFERENCES <tablename> [( <colnames...> )]
  COLLATE <collationname>

Zone configurations:
  DISCARD
  USING <var> = <expr> [, ...]
  USING <var> = COPY FROM PARENT [, ...]
  { TO | = } <expr>

`,
		//line sql.y: 1153
		SeeAlso: `WEBDOCS/alter-table.html
`,
	},
	//line sql.y: 1167
	`ALTER PARTITION`: {
		ShortDescription: `apply zone configurations to a partition`,
		//line sql.y: 1168
		Category: hDDL,
		//line sql.y: 1169
		Text: `
ALTER PARTITION <name> <command>

Commands:
  ALTER PARTITION ... OF TABLE ... CONFIGURE ZONE <zoneconfig>
  ALTER PARTITION ... OF INDEX ... CONFIGURE ZONE <zoneconfig>

Zone configurations:
  DISCARD
  USING <var> = <expr> [, ...]
  USING <var> = COPY FROM PARENT [, ...]
  { TO | = } <expr>

`,
		//line sql.y: 1182
		SeeAlso: `WEBDOCS/configure-zone.html
`,
	},
	//line sql.y: 1187
	`ALTER VIEW`: {
		ShortDescription: `change the definition of a view`,
		//line sql.y: 1188
		Category: hDDL,
		//line sql.y: 1189
		Text: `
ALTER VIEW [IF EXISTS] <name> RENAME TO <newname>
`,
		//line sql.y: 1191
		SeeAlso: `WEBDOCS/alter-view.html
`,
	},
	//line sql.y: 1198
	`ALTER SEQUENCE`: {
		ShortDescription: `change the definition of a sequence`,
		//line sql.y: 1199
		Category: hDDL,
		//line sql.y: 1200
		Text: `
ALTER SEQUENCE [IF EXISTS] <name>
  [INCREMENT <increment>]
  [MINVALUE <minvalue> | NO MINVALUE]
  [MAXVALUE <maxvalue> | NO MAXVALUE]
  [START <start>]
  [[NO] CYCLE]
ALTER SEQUENCE [IF EXISTS] <name> RENAME TO <newname>
`,
	},
	//line sql.y: 1223
	`ALTER USER`: {
		ShortDescription: `change user properties`,
		//line sql.y: 1224
		Category: hPriv,
		//line sql.y: 1225
		Text: `
ALTER USER [IF EXISTS] <name> WITH PASSWORD <password>
`,
		//line sql.y: 1227
		SeeAlso: `CREATE USER
`,
	},
	//line sql.y: 1232
	`ALTER DATABASE`: {
		ShortDescription: `change the definition of a database`,
		//line sql.y: 1233
		Category: hDDL,
		//line sql.y: 1234
		Text: `
ALTER DATABASE <name> RENAME TO <newname>
`,
		//line sql.y: 1236
		SeeAlso: `WEBDOCS/alter-database.html
`,
	},
	//line sql.y: 1244
	`ALTER RANGE`: {
		ShortDescription: `change the parameters of a range`,
		//line sql.y: 1245
		Category: hDDL,
		//line sql.y: 1246
		Text: `
ALTER RANGE <zonename> <command>

Commands:
  ALTER RANGE ... CONFIGURE ZONE <zoneconfig>

Zone configurations:
  DISCARD
  USING <var> = <expr> [, ...]
  USING <var> = COPY FROM PARENT [, ...]
  { TO | = } <expr>

`,
		//line sql.y: 1258
		SeeAlso: `ALTER TABLE
`,
	},
	//line sql.y: 1263
	`ALTER INDEX`: {
		ShortDescription: `change the definition of an index`,
		//line sql.y: 1264
		Category: hDDL,
		//line sql.y: 1265
		Text: `
ALTER INDEX [IF EXISTS] <idxname> <command>

Commands:
  ALTER INDEX ... RENAME TO <newname>
  ALTER INDEX ... SPLIT AT <selectclause> [WITH EXPIRATION <expr>]
  ALTER INDEX ... UNSPLIT AT <selectclause>
  ALTER INDEX ... UNSPLIT ALL
  ALTER INDEX ... SCATTER [ FROM ( <exprs...> ) TO ( <exprs...> ) ]

Zone configurations:
  DISCARD
  USING <var> = <expr> [, ...]
  USING <var> = COPY FROM PARENT [, ...]
  { TO | = } <expr>

`,
		//line sql.y: 1281
		SeeAlso: `WEBDOCS/alter-index.html
`,
	},
	//line sql.y: 1762
	`BACKUP`: {
		ShortDescription: `back up data to external storage`,
		//line sql.y: 1763
		Category: hCCL,
		//line sql.y: 1764
		Text: `
BACKUP <targets...> TO <location...>
       [ AS OF SYSTEM TIME <expr> ]
       [ INCREMENTAL FROM <location...> ]
       [ WITH <option> [= <value>] [, ...] ]

Targets:
   TABLE <pattern> [, ...]
   DATABASE <databasename> [, ...]

Location:
   "[scheme]://[host]/[path to backup]?[parameters]"

Options:
   INTO_DB
   SKIP_MISSING_FOREIGN_KEYS

`,
		//line sql.y: 1781
		SeeAlso: `RESTORE, WEBDOCS/backup.html
`,
	},
	//line sql.y: 1789
	`RESTORE`: {
		ShortDescription: `restore data from external storage`,
		//line sql.y: 1790
		Category: hCCL,
		//line sql.y: 1791
		Text: `
RESTORE <targets...> FROM <location...>
        [ AS OF SYSTEM TIME <expr> ]
        [ WITH <option> [= <value>] [, ...] ]

Targets:
   TABLE <pattern> [, ...]
   DATABASE <databasename> [, ...]

Locations:
   "[scheme]://[host]/[path to backup]?[parameters]"

Options:
   INTO_DB
   SKIP_MISSING_FOREIGN_KEYS

`,
		//line sql.y: 1807
		SeeAlso: `BACKUP, WEBDOCS/restore.html
`,
	},
	//line sql.y: 1845
	`IMPORT`: {
		ShortDescription: `load data from file in a distributed manner`,
		//line sql.y: 1846
		Category: hCCL,
		//line sql.y: 1847
		Text: `
-- Import both schema and table data:
IMPORT [ TABLE <tablename> FROM ]
       <format> <datafile>
       [ WITH <option> [= <value>] [, ...] ]

-- Import using specific schema, use only table data from external file:
IMPORT TABLE <tablename>
       { ( <elements> ) | CREATE USING <schemafile> }
       <format>
       DATA ( <datafile> [, ...] )
       [ WITH <option> [= <value>] [, ...] ]

Formats:
   CSV
   DELIMITED
   MYSQLDUMP
   PGCOPY
   PGDUMP

Options:
   distributed = '...'
   sstsize = '...'
   temp = '...'
   delimiter = '...'      [CSV, PGCOPY-specific]
   nullif = '...'         [CSV, PGCOPY-specific]
   comment = '...'        [CSV-specific]

`,
		//line sql.y: 1875
		SeeAlso: `CREATE TABLE
`,
	},
	//line sql.y: 1919
	`EXPORT`: {
		ShortDescription: `export data to file in a distributed manner`,
		//line sql.y: 1920
		Category: hCCL,
		//line sql.y: 1921
		Text: `
EXPORT INTO <format> <datafile> [WITH <option> [= value] [,...]] FROM <query>

Formats:
   CSV

Options:
   delimiter = '...'   [CSV-specific]

`,
		//line sql.y: 1930
		SeeAlso: `SELECT
`,
	},
	//line sql.y: 2023
	`CANCEL`: {
		//line sql.y: 2024
		Category: hGroup,
		//line sql.y: 2025
		Text: `CANCEL JOBS, CANCEL QUERIES, CANCEL SESSIONS
`,
	},
	//line sql.y: 2032
	`CANCEL JOBS`: {
		ShortDescription: `cancel background jobs`,
		//line sql.y: 2033
		Category: hMisc,
		//line sql.y: 2034
		Text: `
CANCEL JOBS <selectclause>
CANCEL JOB <jobid>
`,
		//line sql.y: 2037
		SeeAlso: `SHOW JOBS, PAUSE JOBS, RESUME JOBS
`,
	},
	//line sql.y: 2055
	`CANCEL QUERIES`: {
		ShortDescription: `cancel running queries`,
		//line sql.y: 2056
		Category: hMisc,
		//line sql.y: 2057
		Text: `
CANCEL QUERIES [IF EXISTS] <selectclause>
CANCEL QUERY [IF EXISTS] <expr>
`,
		//line sql.y: 2060
		SeeAlso: `SHOW QUERIES
`,
	},
	//line sql.y: 2091
	`CANCEL SESSIONS`: {
		ShortDescription: `cancel open sessions`,
		//line sql.y: 2092
		Category: hMisc,
		//line sql.y: 2093
		Text: `
CANCEL SESSIONS [IF EXISTS] <selectclause>
CANCEL SESSION [IF EXISTS] <sessionid>
`,
		//line sql.y: 2096
		SeeAlso: `SHOW SESSIONS
`,
	},
	//line sql.y: 2168
	`CREATE`: {
		//line sql.y: 2169
		Category: hGroup,
		//line sql.y: 2170
		Text: `
CREATE DATABASE, CREATE TABLE, CREATE INDEX, CREATE TABLE AS,
CREATE USER, CREATE VIEW, CREATE SEQUENCE, CREATE STATISTICS,
CREATE ROLE
`,
	},
	//line sql.y: 2251
	`CREATE STATISTICS`: {
		ShortDescription: `create a new table statistic`,
		//line sql.y: 2252
		Category: hMisc,
		//line sql.y: 2253
		Text: `
CREATE STATISTICS <statisticname>
  [ON <colname> [, ...]]
  FROM <tablename> [AS OF SYSTEM TIME <expr>]
`,
	},
	//line sql.y: 2396
	`DELETE`: {
		ShortDescription: `delete rows from a table`,
		//line sql.y: 2397
		Category: hDML,
		//line sql.y: 2398
		Text: `DELETE FROM <tablename> [WHERE <expr>]
              [ORDER BY <exprs...>]
              [LIMIT <expr>]
              [RETURNING <exprs...>]
`,
		//line sql.y: 2402
		SeeAlso: `WEBDOCS/delete.html
`,
	},
	//line sql.y: 2417
	`DISCARD`: {
		ShortDescription: `reset the session to its initial state`,
		//line sql.y: 2418
		Category: hCfg,
		//line sql.y: 2419
		Text: `DISCARD ALL
`,
	},
	//line sql.y: 2431
	`DROP`: {
		//line sql.y: 2432
		Category: hGroup,
		//line sql.y: 2433
		Text: `
DROP DATABASE, DROP INDEX, DROP TABLE, DROP VIEW, DROP SEQUENCE,
DROP USER, DROP ROLE
`,
	},
	//line sql.y: 2450
	`DROP VIEW`: {
		ShortDescription: `remove a view`,
		//line sql.y: 2451
		Category: hDDL,
		//line sql.y: 2452
		Text: `DROP VIEW [IF EXISTS] <tablename> [, ...] [CASCADE | RESTRICT]
`,
		//line sql.y: 2453
		SeeAlso: `WEBDOCS/drop-index.html
`,
	},
	//line sql.y: 2465
	`DROP SEQUENCE`: {
		ShortDescription: `remove a sequence`,
		//line sql.y: 2466
		Category: hDDL,
		//line sql.y: 2467
		Text: `DROP SEQUENCE [IF EXISTS] <sequenceName> [, ...] [CASCADE | RESTRICT]
`,
		//line sql.y: 2468
		SeeAlso: `DROP
`,
	},
	//line sql.y: 2480
	`DROP TABLE`: {
		ShortDescription: `remove a table`,
		//line sql.y: 2481
		Category: hDDL,
		//line sql.y: 2482
		Text: `DROP TABLE [IF EXISTS] <tablename> [, ...] [CASCADE | RESTRICT]
`,
		//line sql.y: 2483
		SeeAlso: `WEBDOCS/drop-table.html
`,
	},
	//line sql.y: 2495
	`DROP INDEX`: {
		ShortDescription: `remove an index`,
		//line sql.y: 2496
		Category: hDDL,
		//line sql.y: 2497
		Text: `DROP INDEX [IF EXISTS] <idxname> [, ...] [CASCADE | RESTRICT]
`,
		//line sql.y: 2498
		SeeAlso: `WEBDOCS/drop-index.html
`,
	},
	//line sql.y: 2518
	`DROP DATABASE`: {
		ShortDescription: `remove a database`,
		//line sql.y: 2519
		Category: hDDL,
		//line sql.y: 2520
		Text: `DROP DATABASE [IF EXISTS] <databasename> [CASCADE | RESTRICT]
`,
		//line sql.y: 2521
		SeeAlso: `WEBDOCS/drop-database.html
`,
	},
	//line sql.y: 2541
	`DROP USER`: {
		ShortDescription: `remove a user`,
		//line sql.y: 2542
		Category: hPriv,
		//line sql.y: 2543
		Text: `DROP USER [IF EXISTS] <user> [, ...]
`,
		//line sql.y: 2544
		SeeAlso: `CREATE USER, SHOW USERS
`,
	},
	//line sql.y: 2556
	`DROP ROLE`: {
		ShortDescription: `remove a role`,
		//line sql.y: 2557
		Category: hPriv,
		//line sql.y: 2558
		Text: `DROP ROLE [IF EXISTS] <role> [, ...]
`,
		//line sql.y: 2559
		SeeAlso: `CREATE ROLE, SHOW ROLES
`,
	},
	//line sql.y: 2583
	`EXPLAIN`: {
		ShortDescription: `show the logical plan of a query`,
		//line sql.y: 2584
		Category: hMisc,
		//line sql.y: 2585
		Text: `
EXPLAIN <statement>
EXPLAIN ([PLAN ,] <planoptions...> ) <statement>
EXPLAIN [ANALYZE] (DISTSQL) <statement>
EXPLAIN ANALYZE [(DISTSQL)] <statement>

Explainable statements:
    SELECT, CREATE, DROP, ALTER, INSERT, UPSERT, UPDATE, DELETE,
    SHOW, EXPLAIN

Plan options:
    TYPES, VERBOSE, OPT

`,
		//line sql.y: 2598
		SeeAlso: `WEBDOCS/explain.html
`,
	},
	//line sql.y: 2673
	`PREPARE`: {
		ShortDescription: `prepare a statement for later execution`,
		//line sql.y: 2674
		Category: hMisc,
		//line sql.y: 2675
		Text: `PREPARE <name> [ ( <types...> ) ] AS <query>
`,
		//line sql.y: 2676
		SeeAlso: `EXECUTE, DEALLOCATE, DISCARD
`,
	},
	//line sql.y: 2707
	`EXECUTE`: {
		ShortDescription: `execute a statement prepared previously`,
		//line sql.y: 2708
		Category: hMisc,
		//line sql.y: 2709
		Text: `EXECUTE <name> [ ( <exprs...> ) ]
`,
		//line sql.y: 2710
		SeeAlso: `PREPARE, DEALLOCATE, DISCARD
`,
	},
	//line sql.y: 2740
	`DEALLOCATE`: {
		ShortDescription: `remove a prepared statement`,
		//line sql.y: 2741
		Category: hMisc,
		//line sql.y: 2742
		Text: `DEALLOCATE [PREPARE] { <name> | ALL }
`,
		//line sql.y: 2743
		SeeAlso: `PREPARE, EXECUTE, DISCARD
`,
	},
	//line sql.y: 2763
	`GRANT`: {
		ShortDescription: `define access privileges and role memberships`,
		//line sql.y: 2764
		Category: hPriv,
		//line sql.y: 2765
		Text: `
Grant privileges:
  GRANT {ALL | <privileges...> } ON <targets...> TO <grantees...>
Grant role membership (CCL only):
  GRANT <roles...> TO <grantees...> [WITH ADMIN OPTION]

Privileges:
  CREATE, DROP, GRANT, SELECT, INSERT, DELETE, UPDATE

Targets:
  DATABASE <databasename> [, ...]
  [TABLE] [<databasename> .] { <tablename> | * } [, ...]

`,
		//line sql.y: 2778
		SeeAlso: `REVOKE, WEBDOCS/grant.html
`,
	},
	//line sql.y: 2794
	`REVOKE`: {
		ShortDescription: `remove access privileges and role memberships`,
		//line sql.y: 2795
		Category: hPriv,
		//line sql.y: 2796
		Text: `
Revoke privileges:
  REVOKE {ALL | <privileges...> } ON <targets...> FROM <grantees...>
Revoke role membership (CCL only):
  REVOKE [ADMIN OPTION FOR] <roles...> FROM <grantees...>

Privileges:
  CREATE, DROP, GRANT, SELECT, INSERT, DELETE, UPDATE

Targets:
  DATABASE <databasename> [, <databasename>]...
  [TABLE] [<databasename> .] { <tablename> | * } [, ...]

`,
		//line sql.y: 2809
		SeeAlso: `GRANT, WEBDOCS/revoke.html
`,
	},
	//line sql.y: 2863
	`RESET`: {
		ShortDescription: `reset a session variable to its default value`,
		//line sql.y: 2864
		Category: hCfg,
		//line sql.y: 2865
		Text: `RESET [SESSION] <var>
`,
		//line sql.y: 2866
		SeeAlso: `RESET CLUSTER SETTING, WEBDOCS/set-vars.html
`,
	},
	//line sql.y: 2878
	`RESET CLUSTER SETTING`: {
		ShortDescription: `reset a cluster setting to its default value`,
		//line sql.y: 2879
		Category: hCfg,
		//line sql.y: 2880
		Text: `RESET CLUSTER SETTING <var>
`,
		//line sql.y: 2881
		SeeAlso: `SET CLUSTER SETTING, RESET
`,
	},
	//line sql.y: 2890
	`USE`: {
		ShortDescription: `set the current database`,
		//line sql.y: 2891
		Category: hCfg,
		//line sql.y: 2892
		Text: `USE <dbname>

"USE <dbname>" is an alias for "SET [SESSION] database = <dbname>".
`,
		//line sql.y: 2895
		SeeAlso: `SET SESSION, WEBDOCS/set-vars.html
`,
	},
	//line sql.y: 2916
	`SCRUB`: {
		ShortDescription: `run checks against databases or tables`,
		//line sql.y: 2917
		Category: hExperimental,
		//line sql.y: 2918
		Text: `
EXPERIMENTAL SCRUB TABLE <table> ...
EXPERIMENTAL SCRUB DATABASE <database>

The various checks that ca be run with SCRUB includes:
  - Physical table data (encoding)
  - Secondary index integrity
  - Constraint integrity (NOT NULL, CHECK, FOREIGN KEY, UNIQUE)
`,
		//line sql.y: 2926
		SeeAlso: `SCRUB TABLE, SCRUB DATABASE
`,
	},
	//line sql.y: 2932
	`SCRUB DATABASE`: {
		ShortDescription: `run scrub checks on a database`,
		//line sql.y: 2933
		Category: hExperimental,
		//line sql.y: 2934
		Text: `
EXPERIMENTAL SCRUB DATABASE <database>
                            [AS OF SYSTEM TIME <expr>]

All scrub checks will be run on the database. This includes:
  - Physical table data (encoding)
  - Secondary index integrity
  - Constraint integrity (NOT NULL, CHECK, FOREIGN KEY, UNIQUE)
`,
		//line sql.y: 2942
		SeeAlso: `SCRUB TABLE, SCRUB
`,
	},
	//line sql.y: 2950
	`SCRUB TABLE`: {
		ShortDescription: `run scrub checks on a table`,
		//line sql.y: 2951
		Category: hExperimental,
		//line sql.y: 2952
		Text: `
SCRUB TABLE <tablename>
            [AS OF SYSTEM TIME <expr>]
            [WITH OPTIONS <option> [, ...]]

Options:
  EXPERIMENTAL SCRUB TABLE ... WITH OPTIONS INDEX ALL
  EXPERIMENTAL SCRUB TABLE ... WITH OPTIONS INDEX (<index>...)
  EXPERIMENTAL SCRUB TABLE ... WITH OPTIONS CONSTRAINT ALL
  EXPERIMENTAL SCRUB TABLE ... WITH OPTIONS CONSTRAINT (<constraint>...)
  EXPERIMENTAL SCRUB TABLE ... WITH OPTIONS PHYSICAL
`,
		//line sql.y: 2963
		SeeAlso: `SCRUB DATABASE, SRUB
`,
	},
	//line sql.y: 3018
	`SET CLUSTER SETTING`: {
		ShortDescription: `change a cluster setting`,
		//line sql.y: 3019
		Category: hCfg,
		//line sql.y: 3020
		Text: `SET CLUSTER SETTING <var> { TO | = } <value>
`,
		//line sql.y: 3021
		SeeAlso: `SHOW CLUSTER SETTING, RESET CLUSTER SETTING, SET SESSION,
WEBDOCS/cluster-settings.html
`,
	},
	//line sql.y: 3042
	`SET SESSION`: {
		ShortDescription: `change a session variable`,
		//line sql.y: 3043
		Category: hCfg,
		//line sql.y: 3044
		Text: `
SET [SESSION] <var> { TO | = } <values...>
SET [SESSION] TIME ZONE <tz>
SET [SESSION] CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL { SNAPSHOT | SERIALIZABLE }
SET [SESSION] TRACING { TO | = } { on | off | cluster | local | kv | results } [,...]

`,
		//line sql.y: 3050
		SeeAlso: `SHOW SESSION, RESET, DISCARD, SHOW, SET CLUSTER SETTING, SET TRANSACTION,
WEBDOCS/set-vars.html
`,
	},
	//line sql.y: 3067
	`SET TRANSACTION`: {
		ShortDescription: `configure the transaction settings`,
		//line sql.y: 3068
		Category: hTxn,
		//line sql.y: 3069
		Text: `
SET [SESSION] TRANSACTION <txnparameters...>

Transaction parameters:
   ISOLATION LEVEL { SNAPSHOT | SERIALIZABLE }
   PRIORITY { LOW | NORMAL | HIGH }

`,
		//line sql.y: 3076
		SeeAlso: `SHOW TRANSACTION, SET SESSION,
WEBDOCS/set-transaction.html
`,
	},
	//line sql.y: 3268
	`SHOW`: {
		//line sql.y: 3269
		Category: hGroup,
		//line sql.y: 3270
		Text: `
SHOW BACKUP, SHOW CLUSTER SETTING, SHOW COLUMNS, SHOW CONSTRAINTS,
SHOW CREATE, SHOW DATABASES, SHOW HISTOGRAM, SHOW INDEXES, SHOW
PARTITIONS, SHOW JOBS, SHOW QUERIES, SHOW ROLES, SHOW SCHEMAS,
SHOW SEQUENCES, SHOW SESSION, SHOW SESSIONS, SHOW STATISTICS,
SHOW SYNTAX, SHOW TABLES, SHOW TRACE SHOW TRANSACTION, SHOW USERS
`,
	},
	//line sql.y: 3305
	`SHOW SESSION`: {
		ShortDescription: `display session variables`,
		//line sql.y: 3306
		Category: hCfg,
		//line sql.y: 3307
		Text: `SHOW [SESSION] { <var> | ALL }
`,
		//line sql.y: 3308
		SeeAlso: `WEBDOCS/show-vars.html
`,
	},
	//line sql.y: 3329
	`SHOW STATISTICS`: {
		ShortDescription: `display table statistics (experimental)`,
		//line sql.y: 3330
		Category: hExperimental,
		//line sql.y: 3331
		Text: `SHOW STATISTICS [USING JSON] FOR TABLE <table_name>

Returns the available statistics for a table.
The statistics can include a histogram ID, which can
be used with SHOW HISTOGRAM.
If USING JSON is specified, the statistics and histograms
are encoded in JSON format.
`,
		//line sql.y: 3338
		SeeAlso: `SHOW HISTOGRAM
`,
	},
	//line sql.y: 3351
	`SHOW HISTOGRAM`: {
		ShortDescription: `display histogram (experimental)`,
		//line sql.y: 3352
		Category: hExperimental,
		//line sql.y: 3353
		Text: `SHOW HISTOGRAM <histogram_id>

Returns the data in the histogram with the
given ID (as returned by SHOW STATISTICS).
`,
		//line sql.y: 3357
		SeeAlso: `SHOW STATISTICS
`,
	},
	//line sql.y: 3370
	`SHOW BACKUP`: {
		ShortDescription: `list backup contents`,
		//line sql.y: 3371
		Category: hCCL,
		//line sql.y: 3372
		Text: `SHOW BACKUP [SCHEMAS|FILES|RANGES] <location>
`,
		//line sql.y: 3373
		SeeAlso: `WEBDOCS/show-backup.html
`,
	},
	//line sql.y: 3408
	`SHOW CLUSTER SETTING`: {
		ShortDescription: `display cluster settings`,
		//line sql.y: 3409
		Category: hCfg,
		//line sql.y: 3410
		Text: `
SHOW CLUSTER SETTING <var>
SHOW ALL CLUSTER SETTINGS
`,
		//line sql.y: 3413
		SeeAlso: `WEBDOCS/cluster-settings.html
`,
	},
	//line sql.y: 3430
	`SHOW COLUMNS`: {
		ShortDescription: `list columns in relation`,
		//line sql.y: 3431
		Category: hDDL,
		//line sql.y: 3432
		Text: `SHOW COLUMNS FROM <tablename>
`,
		//line sql.y: 3433
		SeeAlso: `WEBDOCS/show-columns.html
`,
	},
	//line sql.y: 3441
	`SHOW PARTITIONS`: {
		ShortDescription: `list partition information`,
		//line sql.y: 3442
		Category: hDDL,
		//line sql.y: 3443
		Text: `SHOW PARTITIONS FROM { TABLE <table> | INDEX <index> | DATABASE <database> }
`,
		//line sql.y: 3444
		SeeAlso: `WEBDOCS/show-partitions.html
`,
	},
	//line sql.y: 3464
	`SHOW DATABASES`: {
		ShortDescription: `list databases`,
		//line sql.y: 3465
		Category: hDDL,
		//line sql.y: 3466
		Text: `SHOW DATABASES
`,
		//line sql.y: 3467
		SeeAlso: `WEBDOCS/show-databases.html
`,
	},
	//line sql.y: 3475
	`SHOW GRANTS`: {
		ShortDescription: `list grants`,
		//line sql.y: 3476
		Category: hPriv,
		//line sql.y: 3477
		Text: `
Show privilege grants:
  SHOW GRANTS [ON <targets...>] [FOR <users...>]
Show role grants:
  SHOW GRANTS ON ROLE [<roles...>] [FOR <grantees...>]

`,
		//line sql.y: 3483
		SeeAlso: `WEBDOCS/show-grants.html
`,
	},
	//line sql.y: 3496
	`SHOW INDEXES`: {
		ShortDescription: `list indexes`,
		//line sql.y: 3497
		Category: hDDL,
		//line sql.y: 3498
		Text: `SHOW INDEXES FROM { <tablename> | DATABASE <database_name> }
`,
		//line sql.y: 3499
		SeeAlso: `WEBDOCS/show-index.html
`,
	},
	//line sql.y: 3529
	`SHOW CONSTRAINTS`: {
		ShortDescription: `list constraints`,
		//line sql.y: 3530
		Category: hDDL,
		//line sql.y: 3531
		Text: `SHOW CONSTRAINTS FROM <tablename>
`,
		//line sql.y: 3532
		SeeAlso: `WEBDOCS/show-constraints.html
`,
	},
	//line sql.y: 3545
	`SHOW QUERIES`: {
		ShortDescription: `list running queries`,
		//line sql.y: 3546
		Category: hMisc,
		//line sql.y: 3547
		Text: `SHOW [ALL] [CLUSTER | LOCAL] QUERIES
`,
		//line sql.y: 3548
		SeeAlso: `CANCEL QUERIES
`,
	},
	//line sql.y: 3569
	`SHOW JOBS`: {
		ShortDescription: `list background jobs`,
		//line sql.y: 3570
		Category: hMisc,
		//line sql.y: 3571
		Text: `
SHOW [AUTOMATIC] JOBS
SHOW JOB <jobid>
`,
		//line sql.y: 3574
		SeeAlso: `CANCEL JOBS, PAUSE JOBS, RESUME JOBS
`,
	},
	//line sql.y: 3614
	`SHOW TRACE`: {
		ShortDescription: `display an execution trace`,
		//line sql.y: 3615
		Category: hMisc,
		//line sql.y: 3616
		Text: `
SHOW [COMPACT] [KV] TRACE FOR SESSION
`,
		//line sql.y: 3618
		SeeAlso: `EXPLAIN
`,
	},
	//line sql.y: 3641
	`SHOW SESSIONS`: {
		ShortDescription: `list open client sessions`,
		//line sql.y: 3642
		Category: hMisc,
		//line sql.y: 3643
		Text: `SHOW [ALL] [CLUSTER | LOCAL] SESSIONS
`,
		//line sql.y: 3644
		SeeAlso: `CANCEL SESSIONS
`,
	},
	//line sql.y: 3657
	`SHOW TABLES`: {
		ShortDescription: `list tables`,
		//line sql.y: 3658
		Category: hDDL,
		//line sql.y: 3659
		Text: `SHOW TABLES [FROM <databasename> [ . <schemaname> ] ] [WITH COMMENT]
`,
		//line sql.y: 3660
		SeeAlso: `WEBDOCS/show-tables.html
`,
	},
	//line sql.y: 3692
	`SHOW SCHEMAS`: {
		ShortDescription: `list schemas`,
		//line sql.y: 3693
		Category: hDDL,
		//line sql.y: 3694
		Text: `SHOW SCHEMAS [FROM <databasename> ]
`,
	},
	//line sql.y: 3706
	`SHOW SEQUENCES`: {
		ShortDescription: `list sequences`,
		//line sql.y: 3707
		Category: hDDL,
		//line sql.y: 3708
		Text: `SHOW SEQUENCES [FROM <databasename> ]
`,
	},
	//line sql.y: 3720
	`SHOW SYNTAX`: {
		ShortDescription: `analyze SQL syntax`,
		//line sql.y: 3721
		Category: hMisc,
		//line sql.y: 3722
		Text: `SHOW SYNTAX <string>
`,
	},
	//line sql.y: 3731
	`SHOW TRANSACTION`: {
		ShortDescription: `display current transaction properties`,
		//line sql.y: 3732
		Category: hCfg,
		//line sql.y: 3733
		Text: `SHOW TRANSACTION {ISOLATION LEVEL | PRIORITY | STATUS}
`,
		//line sql.y: 3734
		SeeAlso: `WEBDOCS/show-transaction.html
`,
	},
	//line sql.y: 3753
	`SHOW CREATE`: {
		ShortDescription: `display the CREATE statement for a table, sequence or view`,
		//line sql.y: 3754
		Category: hDDL,
		//line sql.y: 3755
		Text: `SHOW CREATE [ TABLE | SEQUENCE | VIEW ] <tablename>
`,
		//line sql.y: 3756
		SeeAlso: `WEBDOCS/show-create-table.html
`,
	},
	//line sql.y: 3774
	`SHOW USERS`: {
		ShortDescription: `list defined users`,
		//line sql.y: 3775
		Category: hPriv,
		//line sql.y: 3776
		Text: `SHOW USERS
`,
		//line sql.y: 3777
		SeeAlso: `CREATE USER, DROP USER, WEBDOCS/show-users.html
`,
	},
	//line sql.y: 3785
	`SHOW ROLES`: {
		ShortDescription: `list defined roles`,
		//line sql.y: 3786
		Category: hPriv,
		//line sql.y: 3787
		Text: `SHOW ROLES
`,
		//line sql.y: 3788
		SeeAlso: `CREATE ROLE, DROP ROLE
`,
	},
	//line sql.y: 3844
	`SHOW RANGES`: {
		ShortDescription: `list ranges`,
		//line sql.y: 3845
		Category: hMisc,
		//line sql.y: 3846
		Text: `
SHOW RANGES FROM TABLE <tablename>
SHOW RANGES FROM INDEX [ <tablename> @ ] <indexname>
`,
	},
	//line sql.y: 4083
	`PAUSE JOBS`: {
		ShortDescription: `pause background jobs`,
		//line sql.y: 4084
		Category: hMisc,
		//line sql.y: 4085
		Text: `
PAUSE JOBS <selectclause>
PAUSE JOB <jobid>
`,
		//line sql.y: 4088
		SeeAlso: `SHOW JOBS, CANCEL JOBS, RESUME JOBS
`,
	},
	//line sql.y: 4105
	`CREATE TABLE`: {
		ShortDescription: `create a new table`,
		//line sql.y: 4106
		Category: hDDL,
		//line sql.y: 4107
		Text: `
CREATE TABLE [IF NOT EXISTS] <tablename> ( <elements...> ) [<interleave>]
CREATE TABLE [IF NOT EXISTS] <tablename> [( <colnames...> )] AS <source>

Table elements:
   <name> <type> [<qualifiers...>]
   [UNIQUE | INVERTED] INDEX [<name>] ( <colname> [ASC | DESC] [, ...] )
                           [STORING ( <colnames...> )] [<interleave>]
   FAMILY [<name>] ( <colnames...> )
   [CONSTRAINT <name>] <constraint>

Table constraints:
   PRIMARY KEY ( <colnames...> )
   FOREIGN KEY ( <colnames...> ) REFERENCES <tablename> [( <colnames...> )] [ON DELETE {NO ACTION | RESTRICT}] [ON UPDATE {NO ACTION | RESTRICT}]
   UNIQUE ( <colnames... ) [STORING ( <colnames...> )] [<interleave>]
   CHECK ( <expr> )

Column qualifiers:
  [CONSTRAINT <constraintname>] {NULL | NOT NULL | UNIQUE | PRIMARY KEY | CHECK (<expr>) | DEFAULT <expr>}
  FAMILY <familyname>, CREATE [IF NOT EXISTS] FAMILY [<familyname>]
  REFERENCES <tablename> [( <colnames...> )] [ON DELETE {NO ACTION | RESTRICT}] [ON UPDATE {NO ACTION | RESTRICT}]
  COLLATE <collationname>
  AS ( <expr> ) STORED

Interleave clause:
   INTERLEAVE IN PARENT <tablename> ( <colnames...> ) [CASCADE | RESTRICT]

`,
		//line sql.y: 4134
		SeeAlso: `SHOW TABLES, CREATE VIEW, SHOW CREATE,
WEBDOCS/create-table.html
WEBDOCS/create-table-as.html
`,
	},
	//line sql.y: 4823
	`CREATE SEQUENCE`: {
		ShortDescription: `create a new sequence`,
		//line sql.y: 4824
		Category: hDDL,
		//line sql.y: 4825
		Text: `
CREATE SEQUENCE <seqname>
  [INCREMENT <increment>]
  [MINVALUE <minvalue> | NO MINVALUE]
  [MAXVALUE <maxvalue> | NO MAXVALUE]
  [START [WITH] <start>]
  [CACHE <cache>]
  [NO CYCLE]
  [VIRTUAL]

`,
		//line sql.y: 4835
		SeeAlso: `CREATE TABLE
`,
	},
	//line sql.y: 4882
	`TRUNCATE`: {
		ShortDescription: `empty one or more tables`,
		//line sql.y: 4883
		Category: hDML,
		//line sql.y: 4884
		Text: `TRUNCATE [TABLE] <tablename> [, ...] [CASCADE | RESTRICT]
`,
		//line sql.y: 4885
		SeeAlso: `WEBDOCS/truncate.html
`,
	},
	//line sql.y: 4893
	`CREATE USER`: {
		ShortDescription: `define a new user`,
		//line sql.y: 4894
		Category: hPriv,
		//line sql.y: 4895
		Text: `CREATE USER [IF NOT EXISTS] <name> [ [WITH] PASSWORD <passwd> ]
`,
		//line sql.y: 4896
		SeeAlso: `DROP USER, SHOW USERS, WEBDOCS/create-user.html
`,
	},
	//line sql.y: 4918
	`CREATE ROLE`: {
		ShortDescription: `define a new role`,
		//line sql.y: 4919
		Category: hPriv,
		//line sql.y: 4920
		Text: `CREATE ROLE [IF NOT EXISTS] <name>
`,
		//line sql.y: 4921
		SeeAlso: `DROP ROLE, SHOW ROLES
`,
	},
	//line sql.y: 4939
	`CREATE VIEW`: {
		ShortDescription: `create a new view`,
		//line sql.y: 4940
		Category: hDDL,
		//line sql.y: 4941
		Text: `CREATE VIEW <viewname> [( <colnames...> )] AS <source>
`,
		//line sql.y: 4942
		SeeAlso: `CREATE TABLE, SHOW CREATE, WEBDOCS/create-view.html
`,
	},
	//line sql.y: 4976
	`CREATE INDEX`: {
		ShortDescription: `create a new index`,
		//line sql.y: 4977
		Category: hDDL,
		//line sql.y: 4978
		Text: `
CREATE [UNIQUE | INVERTED] INDEX [IF NOT EXISTS] [<idxname>]
       ON <tablename> ( <colname> [ASC | DESC] [, ...] )
       [STORING ( <colnames...> )] [<interleave>]

Interleave clause:
   INTERLEAVE IN PARENT <tablename> ( <colnames...> ) [CASCADE | RESTRICT]

`,
		//line sql.y: 4986
		SeeAlso: `CREATE TABLE, SHOW INDEXES, SHOW CREATE,
WEBDOCS/create-index.html
`,
	},
	//line sql.y: 5204
	`RELEASE`: {
		ShortDescription: `complete a retryable block`,
		//line sql.y: 5205
		Category: hTxn,
		//line sql.y: 5206
		Text: `RELEASE [SAVEPOINT] cockroach_restart
`,
		//line sql.y: 5207
		SeeAlso: `SAVEPOINT, WEBDOCS/savepoint.html
`,
	},
	//line sql.y: 5215
	`RESUME JOBS`: {
		ShortDescription: `resume background jobs`,
		//line sql.y: 5216
		Category: hMisc,
		//line sql.y: 5217
		Text: `
RESUME JOBS <selectclause>
RESUME JOB <jobid>
`,
		//line sql.y: 5220
		SeeAlso: `SHOW JOBS, CANCEL JOBS, PAUSE JOBS
`,
	},
	//line sql.y: 5237
	`SAVEPOINT`: {
		ShortDescription: `start a retryable block`,
		//line sql.y: 5238
		Category: hTxn,
		//line sql.y: 5239
		Text: `SAVEPOINT cockroach_restart
`,
		//line sql.y: 5240
		SeeAlso: `RELEASE, WEBDOCS/savepoint.html
`,
	},
	//line sql.y: 5255
	`BEGIN`: {
		ShortDescription: `start a transaction`,
		//line sql.y: 5256
		Category: hTxn,
		//line sql.y: 5257
		Text: `
BEGIN [TRANSACTION] [ <txnparameter> [[,] ...] ]
START TRANSACTION [ <txnparameter> [[,] ...] ]

Transaction parameters:
   ISOLATION LEVEL { SNAPSHOT | SERIALIZABLE }
   PRIORITY { LOW | NORMAL | HIGH }

`,
		//line sql.y: 5265
		SeeAlso: `COMMIT, ROLLBACK, WEBDOCS/begin-transaction.html
`,
	},
	//line sql.y: 5278
	`COMMIT`: {
		ShortDescription: `commit the current transaction`,
		//line sql.y: 5279
		Category: hTxn,
		//line sql.y: 5280
		Text: `
COMMIT [TRANSACTION]
END [TRANSACTION]
`,
		//line sql.y: 5283
		SeeAlso: `BEGIN, ROLLBACK, WEBDOCS/commit-transaction.html
`,
	},
	//line sql.y: 5307
	`ROLLBACK`: {
		ShortDescription: `abort the current transaction`,
		//line sql.y: 5308
		Category: hTxn,
		//line sql.y: 5309
		Text: `ROLLBACK [TRANSACTION] [TO [SAVEPOINT] cockroach_restart]
`,
		//line sql.y: 5310
		SeeAlso: `BEGIN, COMMIT, SAVEPOINT, WEBDOCS/rollback-transaction.html
`,
	},
	//line sql.y: 5428
	`CREATE DATABASE`: {
		ShortDescription: `create a new database`,
		//line sql.y: 5429
		Category: hDDL,
		//line sql.y: 5430
		Text: `CREATE DATABASE [IF NOT EXISTS] <name>
`,
		//line sql.y: 5431
		SeeAlso: `WEBDOCS/create-database.html
`,
	},
	//line sql.y: 5500
	`INSERT`: {
		ShortDescription: `create new rows in a table`,
		//line sql.y: 5501
		Category: hDML,
		//line sql.y: 5502
		Text: `
INSERT INTO <tablename> [[AS] <name>] [( <colnames...> )]
       <selectclause>
       [ON CONFLICT [( <colnames...> )] {DO UPDATE SET ... [WHERE <expr>] | DO NOTHING}]
       [RETURNING <exprs...>]
`,
		//line sql.y: 5507
		SeeAlso: `UPSERT, UPDATE, DELETE, WEBDOCS/insert.html
`,
	},
	//line sql.y: 5526
	`UPSERT`: {
		ShortDescription: `create or replace rows in a table`,
		//line sql.y: 5527
		Category: hDML,
		//line sql.y: 5528
		Text: `
UPSERT INTO <tablename> [AS <name>] [( <colnames...> )]
       <selectclause>
       [RETURNING <exprs...>]
`,
		//line sql.y: 5532
		SeeAlso: `INSERT, UPDATE, DELETE, WEBDOCS/upsert.html
`,
	},
	//line sql.y: 5639
	`UPDATE`: {
		ShortDescription: `update rows of a table`,
		//line sql.y: 5640
		Category: hDML,
		//line sql.y: 5641
		Text: `
UPDATE <tablename> [[AS] <name>]
       SET ...
       [WHERE <expr>]
       [ORDER BY <exprs...>]
       [LIMIT <expr>]
       [RETURNING <exprs...>]
`,
		//line sql.y: 5648
		SeeAlso: `INSERT, UPSERT, DELETE, WEBDOCS/update.html
`,
	},
	//line sql.y: 5829
	`<SELECTCLAUSE>`: {
		ShortDescription: `access tabular data`,
		//line sql.y: 5830
		Category: hDML,
		//line sql.y: 5831
		Text: `
Select clause:
  TABLE <tablename>
  VALUES ( <exprs...> ) [ , ... ]
  SELECT ... [ { INTERSECT | UNION | EXCEPT } [ ALL | DISTINCT ] <selectclause> ]
`,
	},
	//line sql.y: 5842
	`SELECT`: {
		ShortDescription: `retrieve rows from a data source and compute a result`,
		//line sql.y: 5843
		Category: hDML,
		//line sql.y: 5844
		Text: `
SELECT [DISTINCT [ ON ( <expr> [ , ... ] ) ] ]
       { <expr> [[AS] <name>] | [ [<dbname>.] <tablename>. ] * } [, ...]
       [ FROM <source> ]
       [ WHERE <expr> ]
       [ GROUP BY <expr> [ , ... ] ]
       [ HAVING <expr> ]
       [ WINDOW <name> AS ( <definition> ) ]
       [ { UNION | INTERSECT | EXCEPT } [ ALL | DISTINCT ] <selectclause> ]
       [ ORDER BY <expr> [ ASC | DESC ] [, ...] ]
       [ LIMIT { <expr> | ALL } ]
       [ OFFSET <expr> [ ROW | ROWS ] ]
`,
		//line sql.y: 5856
		SeeAlso: `WEBDOCS/select-clause.html
`,
	},
	//line sql.y: 5931
	`TABLE`: {
		ShortDescription: `select an entire table`,
		//line sql.y: 5932
		Category: hDML,
		//line sql.y: 5933
		Text: `TABLE <tablename>
`,
		//line sql.y: 5934
		SeeAlso: `SELECT, VALUES, WEBDOCS/table-expressions.html
`,
	},
	//line sql.y: 6208
	`VALUES`: {
		ShortDescription: `select a given set of values`,
		//line sql.y: 6209
		Category: hDML,
		//line sql.y: 6210
		Text: `VALUES ( <exprs...> ) [, ...]
`,
		//line sql.y: 6211
		SeeAlso: `SELECT, TABLE, WEBDOCS/table-expressions.html
`,
	},
	//line sql.y: 6320
	`<SOURCE>`: {
		ShortDescription: `define a data source for SELECT`,
		//line sql.y: 6321
		Category: hDML,
		//line sql.y: 6322
		Text: `
Data sources:
  <tablename> [ @ { <idxname> | <indexflags> } ]
  <tablefunc> ( <exprs...> )
  ( { <selectclause> | <source> } )
  <source> [AS] <alias> [( <colnames...> )]
  <source> [ <jointype> ] JOIN <source> ON <expr>
  <source> [ <jointype> ] JOIN <source> USING ( <colnames...> )
  <source> NATURAL [ <jointype> ] JOIN <source>
  <source> CROSS JOIN <source>
  <source> WITH ORDINALITY
  '[' EXPLAIN ... ']'
  '[' SHOW ... ']'

Index flags:
  '{' FORCE_INDEX = <idxname> [, ...] '}'
  '{' NO_INDEX_JOIN [, ...] '}'
  '{' IGNORE_FOREIGN_KEYS [, ...] '}'

Join types:
  { INNER | { LEFT | RIGHT | FULL } [OUTER] } [ { HASH | MERGE | LOOKUP } ]

`,
		//line sql.y: 6344
		SeeAlso: `WEBDOCS/table-expressions.html
`,
	},
}
